"""empty message

Revision ID: 16fae3a0d5ce
Revises: 90a56d7adb08
Create Date: 2021-01-09 22:32:55.985423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fae3a0d5ce'
down_revision = '90a56d7adb08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('venues', sa.Column('date_created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'date_created')
    op.drop_column('shows', 'date_created')
    # ### end Alembic commands ###
