"""empty message

Revision ID: 308637a1dcaa
Revises: 16fae3a0d5ce
Create Date: 2021-01-09 22:33:49.468812

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '308637a1dcaa'
down_revision = '16fae3a0d5ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.drop_column('shows', 'date_created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'date_created')
    # ### end Alembic commands ###
