"""empty message

Revision ID: 873abca8fd81
Revises: 308637a1dcaa
Create Date: 2021-01-10 00:09:47.173023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '873abca8fd81'
down_revision = '308637a1dcaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(timezone=True), nullable=True),
    sa.Column('end_time', sa.Time(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('availabilities')
    # ### end Alembic commands ###
